apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "tensegrity.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-default
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "tensegrity.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
