apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: ghcr.io/fastforgeinc/tensegrity
  newTag: latest

patches:
- path: manager_auth_proxy_patch.yaml
