resources:
- ../crd
- ../rbac
- ../manager
- ../webhook
- certificate.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: patches/manager_webhook_patch.yaml
- path: patches/webhookcainjection_patch.yaml

- path: patches/webhook_in_k8s_deployments.yaml
- path: patches/webhook_in_k8s_statefulsets.yaml
- path: patches/webhook_in_k8s_daemonsets.yaml
- path: patches/webhook_in__statics.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

- path: patches/cainjection_in_k8s_deployments.yaml
- path: patches/cainjection_in_k8s_statefulsets.yaml
- path: patches/cainjection_in_k8s_daemonsets.yaml
- path: patches/cainjection_in__statics.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch
