apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout-sample-api
spec:
  rules:
    - host: api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollout-sample-api
                port:
                  name: http
---

apiVersion: v1
kind: Service
metadata:
  name: rollout-sample-api
spec:
  selector:
    app.kubernetes.io/name: rollout-sample-api
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
---

apiVersion: argo.tensegrity.fastforge.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: rollout-sample-api
  name: rollout-sample-api
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 10 }
        - setWeight: 50
        - pause: { duration: 10 }
        - setWeight: 75
        - pause: { duration: 10 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rollout-sample-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rollout-sample-api
    spec:
      containers:
        - name: rollout-sample-api
          image: registry.k8s.io/e2e-test-images/agnhost:2.38
          command:
            - /agnhost
            - netexec
            - --http-port
            - "8080"
          readinessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 10
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  consumes:
    - apiVersion: tensegrity.fastforge.io/v1alpha1
      kind: Static
      name: static-sample-database
      maps:
        DATABASE_HOST: host
        DATABASE_PORT: port
        DATABASE_NAME: name
        DATABASE_USER: user
        DATABASE_PASSWORD: password
  produces:
    - key: http-host
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      fieldPath: '{ .spec.rules[0].host }.{ .metadata.namespace }'
    - key: http-port
      apiVersion: v1
      kind: Service
      fieldPath: '{ .spec.ports[?(@.name=="http")].port }'
      sensitive: true
