apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
    - host: api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
---
apiVersion: argo.tensegrity.fastforge.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 40
        - pause: { duration: 10 }
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: registry.k8s.io/e2e-test-images/agnhost:2.38
          command:
            - /agnhost
            - netexec
            - --http-port
            - "8080"
          readinessProbe:
            httpGet:
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 10
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#  consumes:
#    - apiVersion: tensegrity.fastforge.io
#      kind: Static
#      name: static-sample
#      maps:
#        DATABASE_HOST: host
#        DATABASE_PORT: port
#        DATABASE_NAME: name
#        DATABASE_USER: user
#        DATABASE_PASSWORD: password
  produces:
    - key: http-host
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      fieldPath: '{ .spec.rules[0].host }.{ .metadata.namespace }'
    - key: http-port
      apiVersion: v1
      kind: Service
      fieldPath: '{ .spec.ports[?(@.name=="http")].port }'
      sensitive: true
