---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - daemonsets/finalizers
  verbs:
  - update
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - daemonsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
