# permissions for end users to edit statefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statefulset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tensegrity
    app.kubernetes.io/part-of: tensegrity
    app.kubernetes.io/managed-by: kustomize
  name: statefulset-editor-role
rules:
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensegrity.fastforge.io
  resources:
  - statefulsets/status
  verbs:
  - get
