//go:build !ignore_autogenerated

/*
Copyright 2024 FastForge Inc. support@fastforge.com.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumedKeyStatus) DeepCopyInto(out *ConsumedKeyStatus) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	if in.Delegate != nil {
		in, out := &in.Delegate, &out.Delegate
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumedKeyStatus.
func (in *ConsumedKeyStatus) DeepCopy() *ConsumedKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ConsumedKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumesSpec) DeepCopyInto(out *ConsumesSpec) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumesSpec.
func (in *ConsumesSpec) DeepCopy() *ConsumesSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducedKeyStatus) DeepCopyInto(out *ProducedKeyStatus) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducedKeyStatus.
func (in *ProducedKeyStatus) DeepCopy() *ProducedKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ProducedKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducesSpec) DeepCopyInto(out *ProducesSpec) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducesSpec.
func (in *ProducesSpec) DeepCopy() *ProducesSpec {
	if in == nil {
		return nil
	}
	out := new(ProducesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tensegrity) DeepCopyInto(out *Tensegrity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tensegrity.
func (in *Tensegrity) DeepCopy() *Tensegrity {
	if in == nil {
		return nil
	}
	out := new(Tensegrity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tensegrity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensegrityCondition) DeepCopyInto(out *TensegrityCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensegrityCondition.
func (in *TensegrityCondition) DeepCopy() *TensegrityCondition {
	if in == nil {
		return nil
	}
	out := new(TensegrityCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensegritySpec) DeepCopyInto(out *TensegritySpec) {
	*out = *in
	if in.Delegates != nil {
		in, out := &in.Delegates, &out.Delegates
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Produces != nil {
		in, out := &in.Produces, &out.Produces
		*out = make([]ProducesSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensegritySpec.
func (in *TensegritySpec) DeepCopy() *TensegritySpec {
	if in == nil {
		return nil
	}
	out := new(TensegritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensegrityStatus) DeepCopyInto(out *TensegrityStatus) {
	*out = *in
	if in.Consumed != nil {
		in, out := &in.Consumed, &out.Consumed
		*out = new(ConsumedStatus)
		**out = **in
	}
	if in.ConsumedKeys != nil {
		in, out := &in.ConsumedKeys, &out.ConsumedKeys
		*out = make([]ConsumedKeyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Produced != nil {
		in, out := &in.Produced, &out.Produced
		*out = new(ProducedStatus)
		**out = **in
	}
	if in.ProducedKeys != nil {
		in, out := &in.ProducedKeys, &out.ProducedKeys
		*out = make([]ProducedKeyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TensegrityCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensegrityStatus.
func (in *TensegrityStatus) DeepCopy() *TensegrityStatus {
	if in == nil {
		return nil
	}
	out := new(TensegrityStatus)
	in.DeepCopyInto(out)
	return out
}
