resources:
- bases/k8s.tensegrity.fastforge.io_deployments.yaml
- bases/k8s.tensegrity.fastforge.io_statefulsets.yaml
- bases/k8s.tensegrity.fastforge.io_daemonsets.yaml
- bases/tensegrity.fastforge.io_statics.yaml
#+kubebuilder:scaffold:crdkustomizeresource
