resources:
- bases/k8s.tensegrity.fastforge.io_deployments.yaml
- bases/k8s.tensegrity.fastforge.io_statefulsets.yaml
- bases/k8s.tensegrity.fastforge.io_daemonsets.yaml
- bases/tensegrity.fastforge.io_statics.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/webhook_in_k8s_deployments.yaml
- path: patches/webhook_in_k8s_statefulsets.yaml
- path: patches/webhook_in_k8s_daemonsets.yaml
- path: patches/webhook_in__statics.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

- path: patches/cainjection_in_k8s_deployments.yaml
- path: patches/cainjection_in_k8s_statefulsets.yaml
- path: patches/cainjection_in_k8s_daemonsets.yaml
- path: patches/cainjection_in__statics.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
