name: Build Main
on:
  push:
    branches:
      - 'main'

permissions: {}

jobs:
  controller-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.image.outputs.digest }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Setup Golang
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.24
      -
        uses: docker/setup-qemu-action@v3.2.0
      -
        uses: docker/setup-buildx-action@v3.7.1
      -
        name: Docker container meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/fastforgeinc/tensegrity
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=sha
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push container image
        id: image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          provenance: false
          sbom: false
